name: rave_flutter
description: A new Flutter plugin for making payment with Flutterwave's rave.
version: 0.0.9-alpha+2
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/rave_flutter
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.0.0
  intl: ^0.19.0
  dio: ^5.7.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  tripledes:
    git:
      url: https://github.com/coding-master15/tripledes-dart
      ref: b4a4a761ad89c0d709aa2a2d31693ffcb6db8e00
  webview_flutter: ^4.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterwave.rave_flutter
        pluginClass:  RaveFlutterPlugin
      ios:
        pluginClass:  RaveFlutterPlugin

  assets:
    - assets/images/
